### ISSUE TITLE
recearh как сделать аналог swager плюс какие использовать библиотеки

### ISSUE THREAD

**Issue by Ziyakaev** [hhru-school/contracts-tests-admin#106]

**Comment by GavrilenkoValentine** [comment]
В качестве библиотеки подсветки синтаксиса будем использовать ту же библиотеку, которую использует сам seagger-ui: [react-syntax-highlighter](https://github.com/react-syntax-highlighter/react-syntax-highlighter).

Для отображения уровней выпадающего списка будем использовать компонент Bootstrap: `Accordion`
