### ISSUE TITLE
Создать бойлерплейт front-end  приложения

### ISSUE THREAD

**Issue by GavrilenkoValentine** [hhru-school/contracts-tests-admin#7]
Создать шаблонное приложиение из `react-create-app` на базе выбранных библиотек и технологий

Предполагаемый список библиотек:
- [x] TypeScript
- [x] React
- [ ] Redux
- [ ] Redux/RTK
- [x] SWR
- [x] React-Router
- [ ] Antd
- [x] ReactStrap

**Comment by SerDImIgor** [comment]
Это будем использовать 
TypeScript
 React
 Redux
ReactStrap
Про остальное я почитаю и попробую потыкаю

**Comment by SerDImIgor** [comment]
Давай заменим Redux на SWR? В SWR код получается лаконичнее. Там не надо Коньсьёмеров и Редьюсеров разрабытывать. Мне 
```
 const { data, error, isLoading } = useSWR(
    "https://api.github.com/repos/vercel/swr",
    fetcher
  );
```
Мне вот это вообще зашло не надо там мидлвару делать

**Comment by GavrilenkoValentine** [comment]
`Antd` и `ReactStrap` выполняют одинаковую функцию, так что они взаимоисключаемы.
Остановимся тогда на `ReactStrap`
